name: Deploy AFE with Bazel (Direct Push)

on:
  push:
    branches: [ "main" ]

env:
  REGISTRY: ghcr.io
  IMAGE_PREFIX: trading-system

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4

      - name: Get Org Name
        run: echo "ORG=${GITHUB_REPOSITORY_OWNER,,}" >> ${GITHUB_ENV}

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push AFE image to GHCR via Bazel
        run: |
          bazel run //afe:push -- --repository ghcr.io/${{ env.ORG }}/${{ env.IMAGE_PREFIX }}/afe

      - name: Push worker image to GHCR via Bazel
        run: |
          bazel run //worker:push -- --repository ghcr.io/${{ env.ORG }}/${{ env.IMAGE_PREFIX }}/worker
